language: cpp
script: make && ./example
matrix:
    include:
        - compiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
          env: CXX=g++-5
